### ISSUE TITLE
Docker Pull Failing - unknown blob

### ISSUE THREAD

**Issue by domenicbove** [geerlingguy/docker-debian9-ansible#12]
It seems something is not working with the dockerhub registry. This happens when I pull:

```
% docker pull geerlingguy/docker-debian9-ansible
Using default tag: latest
latest: Pulling from geerlingguy/docker-debian9-ansible
4f250268ed6a: Already exists
4a665d6b5506: Pulling fs layer
6d752cc2d6b3: Pulling fs layer
19ae5145211a: Pulling fs layer
de8b4079cca0: Waiting
16f0eb458230: Waiting
3b399e5ae8a5: Waiting
d22866fc0436: Waiting
error pulling image configuration: unknown blob
```

Any ideas? Luckily its simple to build the image locally, but unfortunately my molecule scenarios try to pull each time and are now failing.

**Comment by geerlingguy** [comment]
Yeah, this is really weird, and I'm seeing failures across the board now too :)

I'll re-build on docker hub and see if that fixes it.

Edit: rebuilding now...

Edit 2: build in progress...

Edit 3: build done!

**Comment by geerlingguy** [comment]
@domenicbove - Looks like it's working now. Sorry about Docker Hub's strange behavior :P

**Comment by domenicbove** [comment]
Working fine now, thanks for the quick turn around!
