### ISSUE TITLE
Feature request - new debian10 image

### ISSUE THREAD

**Issue by sseide** [geerlingguy/docker-debian9-ansible#5]
For testing ansible roles it would be really helpful to have a image similiar to the debian8/9 available for upcomming debian 10 (buster) too.

Thanks in advance,
Stefan Seide

**Comment by dmlb2000** [comment]
This is here https://hub.docker.com/r/geerlingguy/docker-debian10-ansible seems fine to me.

**Comment by geerlingguy** [comment]
There is now an image, as @dmlb2000 referenced :)
