### ISSUE TITLE
Running container adversely affects host system.

### ISSUE THREAD

**Issue by dmlb2000** [geerlingguy/docker-debian9-ansible#8]
When starting this container using the documented methods, systemd starts too many things that the host systemd is really taking care of.

 * agettys get started in the container and take over the host ttys (all 6 of them)

This will kick your X11 server on Linux (killing your active user session) if you are running docker in that environment.

I'm running in Ubuntu 18.04

**Comment by jsf9k** [comment]
I see this problem as well, although I don't find it to be a huge issue.  xdm restarts, I start a new terminal and reattach to screen, and pick up right where I left off.

I'm running in Arch, but you would probably see the same behavior in any flavor of linux.

**Comment by markpash** [comment]
Also experiencing the same issue, and I do find it to be quite a big issue. This currently disrupts workflow for me by closing any programs I have open. I would appreciate the PR that fixes this #9 to be merged :)
